### ISSUE TITLE
Iteracrtion 1 - 时间圆环的UI设计

### ISSUE THREAD

**Issue by eValam** [Mobile-Newbie-Group/Mobile-for-life#4]
Wanted output：
完成时间圆环的UI设计，包括圆环的尺寸，位置，各个要素的展示等

**Comment by xiaodongC** [comment]
完成
![5s](https://cloud.githubusercontent.com/assets/13479599/9077711/5b22cb22-3aff-11e5-90b9-63f53a6d026e.png)
